name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # or master, depending on your default branch
  workflow_dispatch:
jobs:
  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-east1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 \
            -t us-east1-docker.pkg.dev/proven-dream-439521-t5/smoke-viewer-repo/hms-smoke-viewer \
            --push .

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: hms-smoke-viewer
          image: us-east1-docker.pkg.dev/proven-dream-439521-t5/smoke-viewer-repo/hms-smoke-viewer
          region: us-east1
        